[target.thumbv7em-none-eabihf]
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "linker=arm-none-eabi-ld",
]
runner = "arm-none-eabi-gdb -q"
# runner = "probe-run --chip STM32F411VETx"

[build]
target = "thumbv7em-none-eabihf"

[run]
target = "thumbv7em-none-eabihf"

[default.gdb]
enabled = true

[default.reset]
halt_afterwards = true
